# Generated by Django 3.0.1 on 2020-01-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='palce_birth',
            new_name='place_birth',
        ),
    ]
