# Generated by Django 3.0.2 on 2020-01-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_dewey_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='nb_tracks_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
