# Generated by Django 3.0.2 on 2020-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200107_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(editable=False, max_length=61),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
