# Generated by Django 3.0.2 on 2020-01-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200107_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['reference']},
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('B', 'Books'), ('M', 'Music'), ('F', 'Film'), ('_', 'Autre')], default='_', max_length=1),
        ),
    ]
