# Generated by Django 3.0.2 on 2020-01-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200108_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('B', 'Books'), ('M', 'Music'), ('F', 'Film'), ('_', 'Autre')], default='B', max_length=1),
        ),
    ]
