# Generated by Django 3.0.2 on 2020-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200108_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(blank=True, choices=[('000', '#000000'), ('100', '#800000'), ('200', '#FF0000'), ('300', '#FF5733'), ('400', '#FFFF00'), ('500', '#008000'), ('600', '#1E90FF'), ('700', '#800080'), ('800', '#cococo'), ('900', '#FFFFFF')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(blank=True, choices=[('black', '#FFFFFF'), ('white', '#000000')], max_length=7, null=True),
        ),
    ]
