# Generated by Django 3.0.2 on 2020-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200110_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewey',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=120, verbose_name="Nom de l'oeuvre"),
        ),
    ]
